apiVersion: v1
kind: Namespace
metadata:
  name: mauricio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mauricio-deployment
  namespace: mauricio
  labels:
    app: app-mauricio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-mauricio
  template:
    metadata:
      labels:
        app: app-mauricio
    spec:
      containers:
      - name: app-mauricio-container
        image: monster9/monster9:1
        ports:
        - containerPort: 5000